### ISSUE TITLE
Extra fields [enhancement]

### ISSUE THREAD

**Issue by amanbolat** [johntdyer/slackrus#10]
## Description
Add some extra fields that will be only sent by hook, but will not change origin entry.
Idea was taken from https://github.com/gemnasium/logrus-postgresql-hook

## How to
```go
// Add Extra field
type SlackrusHook struct {
	Extra          map[string]interface{}
}
// Function to create new entry with extra fields
func (sh *SlackrusHook) newEntry(entry *logrus.Entry) *logrus.Entry {
	//return newEntry
}
```

If you like it, I can open pull request.

**Comment by johntdyer** [comment]
@amanbolat  - Sure, PR's are most certainly welcome !

**Comment by johntdyer** [comment]
Handled in PR #11
