### ISSUE TITLE
add a LICENSE file in slack-go

### ISSUE THREAD

**Issue by Okabe-Junya** [johntdyer/slackrus#19]
please add a LICENSE file in https://github.com/johntdyer/slack-go

## WHY
I am using slackrus, and I get an error with [license-check](https://github.com/google/go-licenses) because the slack-go on which it depends has no license.

**Comment by johntdyer** [comment]
added,  MIT, hope thats cool

**Comment by Okabe-Junya** [comment]
thank you!!

**Comment by Okabe-Junya** [comment]
It didn't work because go.mod was referencing an older version.

To solve this problem, I created a pull request #20
