### ISSUE TITLE
If  logrus.SetFormatter(&logrus.JSONFormatter{}) is set, logging still default in Slack

### ISSUE THREAD

**Issue by jsgoecke** [johntdyer/slackrus#2]
I currently set my logging this way:

``` go
func setLogging() {
    log.SetFormatter(&log.JSONFormatter{})
    log.SetLevel(log.DebugLevel)
    log.AddHook(&slackrus.SlackrusHook{
        HookUrl:        "https://hooks.slack.com/services/foo/bar",
        AcceptedLevels: slackrus.LevelThreshold(log.DebugLevel),
        Channel:        "#conf-log",
        IconEmoji:      ":ghost:",
        Username:       "conf",
    })
}
```

And get this logging on STDOUT:

``` json
{"text":"","username":"conf","icon_url":"","icon_emoji":":ghost:","channel":"#conf-log","unfurl_links":false,"attachments":[{"fallback":"Listening on 3000...","text":"Listening on 3000...","pretext":"","color":"good","fields":null}]}
{"text":"","username":"tropoconf","icon_url":"","icon_emoji":":ghost:","channel":"#conf-log","unfurl_links":false,"attachments":[{"fallback":"Ready!","text":"Ready!","pretext":"","color":"good","fields":null}]}
{"level":"info","msg":"Ready!","time":"2015-01-05T14:56:12-08:00"}
{"level":"info","msg":"Listening on 3000...","time":"2015-01-05T14:56:12-08:00"}
```

But, I only logged the last two "info" messages, not the first two. Further, when set to JSON, I see my messages locally in JSON, but then only see this in the Slack channel:

```
Listening on 3000...

Ready!
```

I would expect to see JSON in my Slack chat with this setting.

**Comment by johntdyer** [comment]
I am not seeing the same thing

## Example.go
```go
package main

import (
	logrus "github.com/Sirupsen/logrus"
	"github.com/johntdyer/slackrus"
	"os"
)

func main() {
	logrus.SetOutput(os.Stderr)
	logrus.SetLevel(logrus.DebugLevel)

	logrus.AddHook(&slackrus.SlackrusHook{
		HookUrl:        "https://hooks.slack.com/services/abc/123/456", 
		AcceptedLevels: slackrus.LevelThreshold(logrus.DebugLevel),
		Channel:        "#slack-testing",
		IconEmoji:      ":ghost:",
		Username:       "foobot",
	})

	logrus.WithFields(logrus.Fields{
		"foo": "bar", "foo2": "bar2",
	}).Warn("this is a warn level message")
	logrus.Info("this is an info level message")
	logrus.Debug("this is a debug level message")
}

```

I get the following output

```log
$ go run example.go                                                                                                          (master⚡)
WARN[0000] this is a warn level message                  foo=bar foo2=bar2
INFO[0001] this is an info level message
DEBU[0002] this is a debug level message

```

**Comment by jaybeecave** [comment]
@johntdyer try using JSON logging? I am getting this problem on slack also where the posts are just text not JSON. I ended up creating a nice txt format for posting my errors to slack

**Comment by johntdyer** [comment]
@jaybeecave  - Afraid I dont use Slack any more personally so I dont have easy access to an account.  Any chance you could submit a PR for this or perhaps concise test cast and I can try to spin up a disposable slack account and do a PR as time allows?

**Comment by amanbolat** [comment]
@jaybeecave Why you need JSON output on slack channel? I also set json formatting, but I'm ok with beautiful text messages on slack. 
Also I don't think that you should fire this hook on log level lower than `ErrorLevel`, because there are some rate limits and often there is a centralized logging server where you can analyze your logs in JSON format, but email/slack/chat and other hooks are just for receiving a Fatal/Panic level logs.

**Comment by johntdyer** [comment]
Going to close this for the time being since it doesnt seem to be an issue any longer
