### ISSUE TITLE
When logging with logrus fields I only see the info/debug/error/warn message in Slack

### ISSUE THREAD

**Issue by jsgoecke** [johntdyer/slackrus#4]
If I do logging like this:

```go
logrus.WithFields(logrus.Fields{"foo": bar"}.Info("Foobar") 
```
I only see "Foobar" logged in Slack, the fields are missing.

**Comment by johntdyer** [comment]
Did u try updating ?  I just pushed a fix for this 

-----
John Dyer
407.474.0214

* Sent from mobile. Please excuse brevity or typographical errors *

**Comment by jsgoecke** [comment]
I confirm this now works with this commit:

https://github.com/johntdyer/slackrus/commit/ba2d43a1fc35eeb3fcb9d8f26914330d3014e56c
