### ISSUE TITLE
case-insensitive import collision for logrus

### ISSUE THREAD

**Issue by kylevanek** [johntdyer/slackrus#9]
It looks like Sirupsen/logrus has updated the import path to have a lowercase "s", I am now seeing this error

case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"

**Comment by sgoodliff** [comment]
Hi,

yep me too, thanks for the package.

**Comment by johntdyer** [comment]
Thanks, pushed a fix... hope it helps

**Comment by sgoodliff** [comment]
Cheers

**Comment by johntdyer** [comment]
This was fixed in 
https://github.com/johntdyer/slackrus/commit/0d54f47427a89687a1245a984fbbffad4dfa1def

Closing this issue out
